language: python
sudo: false
services:
  - redis-server
python:
  - 3.5.2
  - 3.6
  - pypy3.5
install:
  - pip install -U pip setuptools
  - pip install -U pytest-runner pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
  - pip install -U aiohttp aiohttp_apiset "aioredis<1" asynqp crontab ipython
  - pip install codecov
  - python setup.py install
script: py.test --cov=aioworkers

after_success:
  - codecov
