language: python
sudo: false
services: []
python:
  - 3.5.3
  - 3.6
  # - 3.7-dev
  # - pypy3
install:
  - pip install -U pip setuptools pipenv
  - pipenv install -d --skip-lock
  - pip install codecov
script: pytest --cov=aioworkers

after_success:
  - codecov

before_deploy:
  - make aioworkers/version.py

deploy:
  provider: pypi
  user: yttrium
  password:
    secure: hM4+BbKzB8E7lBpjfYdHeTU07a/iimW7vAHPfZCn6rgdhDYQ2GtCDNGzllZSyBnGl28PEVTT+q1RNbrYT+kXD4+tX2AtDMZieCTffqB+qfkUYngeRBv4N5J+OKr/MalvT+Oa6HnD4ST+npuB+4GNQlW39HplKEj3JWTQkEgf7nOHTn37XrnwF/pN7OpmaizCGN+NfJ9xxupTzZ8nbFzzHJVsr2mIJusiAquUTEqzxEMJd9gexm1hbwJWcSDmVR/QavraCZh6yDgTUQWUorAK3e1PmhSudzERrWW2oGpM4Ewe/VOMVwnVECpf0hmGuHG1Pawi5lHbOKD2tuPm3z7m5NBMsczr2Dh8Q5atlQd/h7SauODJu28xE+zzdHCxEIE2F1MoDCV1zVhWpk3nDXtp4p71hEbjQ2O1oa5Wn6pYNgbfiBDbkC6ELcqVp4p2qDJ3Df5eqCNlTi7j1iSKIxTIozHE/O1ACO5K/VL9sf7FEx/XBC+MuRcIcyg9OhBM8SmBaGWBikm9NB7YfroA8YxBGU6XUNmSDtk84rwxxJe1rcEV1zF+bflncX3tNdpiGxBKVyCbnTgTkMrOpnqtsKaEx8BCUYfxYaoKa0FRlYLk9+Nb7hag2j/djSj9ekUskLdYYSRwiofg65qptliwOrKxE6KCU0mdHFNq1Uwv4fnja7I=
  on:
    tags: true
    distributions: sdist
    repo: aioworkers/aioworkers
    condition: $TRAVIS_PYTHON_VERSION = 3.6
  skip_cleanup: true
