language: python
sudo: false
services: []
python:
  - 3.5.3
  - 3.6
  # - pypy3
install:
  - pip install -U pip setuptools
  - pip install -U pytest-runner pytest-aiohttp pytest-pep8 pytest-mock pytest-cov
  - pip install -U 'crontab<0.22' ipython ipykernel
  - pip install codecov
  - python setup.py install
script: pytest tests --cov=aioworkers --doctest-modules aioworkers/humanize.py

after_success:
  - codecov
